site_name: My Docs
repo_url: https://github.com/OpenEnergyPlatform
repo_name: Open Energy Family
theme:
  name: material
  logo: oef-logo-white.png
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false



extra_css:
  - stylesheets/extra.css
    
    # primary: "#1F567D"
